name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE_NAME: shawndengdocker/ibkr_event_daemon
  GITHUB_IMAGE_NAME: ShawnDen-coder/ibkr_event_daemon

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PERSONAL_ACCESS_TOKEN: op://shawndengdev/github_access_token/credential
          DOCKER_USERNAME: shawndengdocker
          DOCKER_TOKEN: op://shawndengdev/dockerhub/credential

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ env.PERSONAL_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{env.DOCKERHUB_IMAGE_NAME}}:latest
            ${{env.DOCKERHUB_IMAGE_NAME}}:${{ github.ref_name}}

      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ${{ env.GITHUB_IMAGE_NAME }}:latest \
            --tag ${{ env.GITHUB_IMAGE_NAME }}:${{ github.ref_name }} \
            ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.ref_name }}